### PR TITLE
Duktape to QuickJS

### LINKED ISSUE #20: wasmer-js Handling Input Output example does not work
First, before I claim there's a bug, are there any undocumented prerequisites needed to get this example working?  For instance, should `duktape` work without first needing to `wapm install` it?

When running the coding shown [here](https://docs.wasmer.io/wasmer-js/node-modules/examples/handling-input-output/wasmer-js-node-modules-handling-input-output), I get a pop-up prompt as expected and if I enter a numeric value, the prompt reappears.  If I then cancel the prompt, the expected value is displayed in both the DOM and the console.

Odd behaviour, but OK...

If I enter any non-numeric value however, the following stack trace appears in the console without any values displayed in either the DOM or the console

```
index.js:119 RuntimeError: unreachable
    at abort (wasm-function[1250]:0xe7264)
    at duk_err_longjmp (wasm-function[440]:0x3629e)
    at duk_err_create_and_throw (wasm-function[23]:0x159a)
    at duk_err_handle_error_fmt (wasm-function[205]:0x1623d)
    at duk__getvar_helper (wasm-function[700]:0x63b40)
    at duk_js_getvar_activation (wasm-function[1173]:0xdbdc2)
    at duk__js_execute_bytecode_inner (wasm-function[1160]:0xd762b)
    at duk_js_execute_bytecode (wasm-function[1146]:0x9dbcb)
    at duk__handle_call_raw (wasm-function[38]:0x2a5d)
    at duk_handle_call_unprotected (wasm-function[33]:0x1d2e)
```

### PR DESCRIPTION
**Pull request by torch2424**
closes #20 

This replaces duktape as the default I/O Application, with QuickJS for the documentation. As Duktape was having issues parsing stdin, and QuickJS handles it fine.

cc @ChrisWhealy 

Screen Shot 2020-01-24 at 5 55 51 PM

### CODE REVIEW

File: docs/wasmer-js/client/examples/handling-input-output/index.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { WasmFs } from '@wasmer/wasmfs';
 import { lowerI64Imports } from "@wasmer/wasm-transformer";
 
 // The file path to the wasi module we want to run
-const wasmFilePath = './static/duktape.wasm';
+const wasmFilePath = './quickjs.wasm';
```
Comment (syrusakbary) [inline docs/wasmer-js/client/examples/handling-input-output/index.js]: Is the path no longer in static?

**Comment by ChrisWhealy** [comment]
I think `.wasm` files need to be in `/static` otherwise `parcel` can't serve them...

File: docs/wasmer-js/client/examples/handling-input-output/index.js (hunk 1 above)
Comment (ChrisWhealy) [reply docs/wasmer-js/client/examples/handling-input-output/index.js]: I think `.wasm` files need to be in `/static` otherwise `parcel` can't serve them...

Comment (torch2424) [reply docs/wasmer-js/client/examples/handling-input-output/index.js]: @syrusakbary @ChrisWhealy 

It's still in the `static/` directory, but this was a typo on my end. If you look at the other examples: 

https://github.com/wasmerio/docs.wasmer.io/blob/master/docs/wasmer-js/client/examples/transforming-wasi-modules/index.js#L7

The example files are in `static/`, but they are served from the root of the website. 

Thus the bug was, I never needed `static/` in the actual asset path 🙃

**Comment by syrusakbary** [comment]
Cool, merging.
